name: Build Android APK (Sara Industries)

on:
  push: { branches: [ "main" ] }
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # Create android/ios if missing
      - name: Ensure android/ and ios/ exist
        run: |
          if [ ! -d "android" ] || [ ! -d "ios" ]; then
            flutter create --platforms=android,ios _tmpapp
            [ ! -d "android" ] && cp -r _tmpapp/android . || true
            [ ! -d "ios" ] && cp -r _tmpapp/ios . || true
          fi

      # Pre-fix the usual build errors
      - name: Patch Android config (AndroidX, SDK levels, exported, namespace, memory)
        run: |
          # AndroidX + memory
          mkdir -p android
          cat >> android/gradle.properties <<'EOF'
          android.useAndroidX=true
          android.enableJetifier=true
          org.gradle.jvmargs=-Xmx2048m -Dkotlin.daemon.jvm.options=-Xmx1024m
          kotlin.code.style=official
          EOF

          # SDK levels
          sed -i 's/minSdkVersion [0-9][0-9]*/minSdkVersion 21/g' android/app/build.gradle || true
          sed -i 's/targetSdkVersion [0-9][0-9]*/targetSdkVersion 34/g' android/app/build.gradle || true
          sed -i 's/compileSdkVersion [0-9][0-9]*/compileSdkVersion 34/g' android/app/build.gradle || true

          # Ensure namespace exists for AGP 8+
          if ! grep -q '^[[:space:]]*namespace[[:space:]]' android/app/build.gradle; then
            sed -i '0,/android {/s//android {\n    namespace "com.sara.gstapp"/' android/app/build.gradle || true
          fi

          # Ensure android:exported="true" on main activity for Android 12+
          MANIFEST=android/app/src/main/AndroidManifest.xml
          if [ -f "$MANIFEST" ]; then
            if grep -q 'android:name="\.MainActivity"' "$MANIFEST" && ! grep -q 'android:exported=' "$MANIFEST"; then
              sed -i 's|<activity android:name="\.MainActivity"|<activity android:name=".MainActivity" android:exported="true"|' "$MANIFEST"
            fi
            if grep -q 'io.flutter.embedding.android.FlutterActivity' "$MANIFEST" && ! grep -q 'android:exported=' "$MANIFEST"; then
              sed -i 's|io.flutter.embedding.android.FlutterActivity"|io.flutter.embedding.android.FlutterActivity" android:exported="true"|' "$MANIFEST"
            fi
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Build release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
